from enum import Enum

class ST_TextLanguage(Enum):
    Afar = "aa"
    Afrikaans = "af"
    Aghem = "agq"
    Akan = "ak"
    Albanian = "sq"
    Alsatian = "gsw"
    Amharic = "am"
    Arabic = "ar"
    Armenian = "hy"
    Assamese = "as"
    Asturian = "ast"
    Asu = "asa"
    AzerbaijaniCyrillic = "az-Cyrl"
    AzerbaijaniLatin = "az"
    Bafia = "ksf"
    Bamanankan = "bm"
    BamanankanLatin = "bm-Latn"
    Bangla = "bn"
    Basaa = "bas"
    Bashkir = "ba"
    Basque = "eu"
    Belarusian = "be"
    Bemba = "bem"
    Bena = "bez"
    Bhojpuri = "bho"
    BhojpuriDevanagari = "bho-Deva"
    Blin = "byn"
    Bodo = "brx"
    BosnianCyrillic = "bs-Cyrl"
    BosnianLatin = "bs-Latn"
    Breton = "br"
    Bulgarian = "bg"
    Burmese = "my"
    Catalan = "ca"
    Cebuano = "ceb"
    CebuanLatin = "ceb-Latn"
    CentralAtlasTamazightArabic = "tzm-Arab"
    CentralAtlasTamazightLatin = "tzm-Latn"
    CentralKurdish = "ku"
    Chakma = "ccp"
    Chechen = "ce"
    Cherokee = "chr"
    Chiga = "cgg"
    ChineseSimplified = "zh-Hans"
    ChineseTraditional = "zh-Hant"
    ChurchSlavic = "cu"
    Chuvash = "cv"
    ChuvashCyrillic = "cv-Cyrl"
    CongoSwahili = "swc"
    Cornish = "kw"
    Corsican = "co"
    Croatian = "hr"
    CroatianLatin = "hr"
    Czech = "cs"
    Danish = "da"
    Dari = "prs"
    Divehi = "dv"
    Duala = "dua"
    Dutch = "nl"
    Dzongkha = "dz"
    Embu = "ebu"
    English = "en"
    Esperanto = "eo"
    Estonian = "et"
    Ewe = "ee"
    Ewondo = "ewo"
    Faroese = "fo"
    Filipino = "fil"
    Finnish = "fi"
    French = "fr"
    Frisian = "fy"
    Friulian = "fur"
    Fulah = "ff"
    FulahLatin = "ff-Latn"
    Galician = "gl"
    Ganda = "lg"
    Georgian = "ka"
    German = "de"
    Greek = "el"
    Greenlandic = "kl"
    Guarani = "gn"
    Gujarati = "gu"
    Gusii = "guz"
    Haryanvi = "bgc"
    HaryanviDevanagari = "bgc-Deva"
    HausaLatin = "ha"
    Hawaiian = "haw"
    Hebrew = "he"
    Hindi = "hi"
    HindiLatin = "hi-Latn"
    Hungarian = "hu"
    Icelandic = "is"
    Igbo = "ig"
    Indonesian = "id"
    Interlingua = "ia"
    InuktitutLatin = "iu"
    InuktitutSyllabics = "iu-Cans"
    Irish = "ga"
    Italian = "it"
    Japanese = "ja"
    Javanese = "jv"
    Jola_Fonyi = "dyo"
    Kabuverdianu = "kea"
    Kabyle = "kab"
    Kaingang = "kgp"
    KaingangLatin = "kgp-Latn"
    Kako = "kkj"
    Kalenjin = "kln"
    Kamba = "kam"
    Kannada = "kn"
    KanuriLatin = "kr-Latn"
    Kashmiri = "ks"
    KashmiriDevanagari = "ks-Deva"
    Kazakh = "kk"
    Khmer = "km"
    Kiche = "quc"
    Kikuyu = "ki"
    Kinyarwanda = "rw"
    Kiswahili = "sw"
    Konkani = "kok"
    Korean = "ko"
    KoyraChiini = "khq"
    KoyraboroSenni = "ses"
    Kwasio = "nmg"
    Kyrgyz = "ky"
    Kurdish = "ku-Arab"
    Lakota = "lkt"
    Langi = "lag"
    Lao = "lo"
    Latin = "la"
    Latvian = "lv"
    Lingala = "ln"
    Lithuanian = "lt"
    LowGerman = "nds"
    LowerSorbian = "dsb"
    Luba_Katanga = "lu"
    Luo = "luo"
    Luxembourgish = "lb"
    Luyia = "luy"
    Macedonian = "mk"
    Machame = "jmc"
    Makhuwa_Meetto = "mgh"
    Makonde = "kde"
    Malagasy = "mg"
    Malay = "ms"
    Malayalam = "ml"
    Maltese = "mt"
    Manx = "gv"
    Maori = "mi"
    Mapudungun = "arn"
    Marathi = "mr"
    Masai = "mas"
    Mazanderani = "mzn"
    Meru = "mer"
    Meta = "mgo"
    Mohawk = "moh"
    MongolianCyrillic = "mn"
    MongolianTraditionalMongolian = "mn-Mong"
    Morisyen = "mfe"
    Mundang = "mua"
    Nko = "nqo"
    Nama = "naq"
    Nepali = "ne"
    Ngiemboon = "nnh"
    Ngomba = "jgo"
    Nheengatu = "yrl"
    NheengatuLatin = "yrl-Latn"
    NorthernLuri = "lrc"
    NorthNdebele = "nd"
    NorwegianBokmal = "no"
    NorwegianNynorsk = "nn"
    NorwegianBokmål = "nb"
    Nuer = "nus"
    Nyankole = "nyn"
    Occitan = "oc"
    Odia = "or"
    Oromo = "om"
    Ossetian = "os"
    Pashto = "ps"
    Persian = "fa"
    Polish = "pl"
    Portuguese = "pt"
    Prussian = "prg-001"
    PseudoLanguage = "qps-ploca"
    Punjabi = "pa"
    Quechua = "quz"
    Rajasthani = "raj"
    RajasthaniDevanagari = "raj-Deva"
    Ripuarian = "ksh"
    Romanian = "ro"
    Romansh = "rm"
    Rombo = "rof"
    Rundi = "rn"
    Russian = "ru"
    Rwa = "rwk"
    Saho = "ssy"
    Sakha = "sah"
    Samburu = "saq"
    SamiInari = "smn"
    SamiLule = "smj"
    SamiNorthern = "se"
    SamiSkolt = "sms"
    SamiSouthern = "sma"
    Sango = "sg"
    Sangu = "sbp"
    Sanskrit = "sa"
    Sardinian = "sc"
    SardinianLatin = "sc-Latn"
    ScottishGaelic = "gd"
    Sena = "seh"
    SerbianCyrillic = "sr-Cyrl"
    SerbianLatin = "sr-Latn"
    SesothosaLeboa = "nso"
    Setswana = "tn"
    Shambala = "ksb"
    Shona = "sn"
    Sindhi = "sd"
    Sinhala = "si"
    Slovak = "sk"
    Slovenian = "sl"
    Soga = "xog"
    Somali = "so"
    Sotho = "st"
    SouthNdebele = "nr"
    SouthernSotho = "st"
    Spanish = "es"
    StandardMoroccanTamazight = "zgh"
    Swati = "ss"
    Swedish = "sv"
    Syriac = "syr"
    Tachelhit = "shi"
    TachelhitLatin = "shi-Latn"
    Taita = "dav"
    TajikCyrillic = "tg"
    TamazightLatin = "tzm"
    Tamil = "ta"
    Tasawaq = "twq"
    Tatar = "tt"
    Telugu = "te"
    Teso = "teo"
    Thai = "th"
    Tibetan = "bo"
    Tigre = "tig"
    Tigrinya = "ti"
    Tongan = "to"
    Tsonga = "ts"
    Turkish = "tr"
    Turkmen = "tk"
    Ukrainian = "uk"
    UpperSorbian = "hsb"
    Urdu = "ur"
    Uyghur = "ug"
    Uzbek = "uz-Arab"
    UzbekCyrillic = "uz-Cyrl"
    UzbekLatin = "uz"
    Vai = "vai"
    VaiLatin = "vai-Latn"
    Valencian = "ca"
    Venda = "ve"
    Vietnamese = "vi"
    Volapük = "vo"
    Vunjo = "vun"
    Walser = "wae"
    Welsh = "cy"
    Wolaytta = "wal"
    Wolof = "wo"
    Xhosa = "xh"
    Yangben = "yav"
    Yi = "ii"
    Yiddish = "yi-001"
    Yoruba = "yo"
    Zarma = "dje"
    Zulu = "zu"

class ST_TextRegion(Enum):
    Djibouti = "DJ"
    Eritrea = "ER"
    Ethiopia = "ET"
    Namibia = "NA"
    South_Africa = "ZA"
    Cameroon = "CM"
    Ghana = "GH"
    Albania = "AL"
    North_Macedonia = "MK"
    France = "FR"
    Liechtenstein = "LI"
    Switzerland = "CH"
    Algeria = "DZ"
    Bahrain = "BH"
    Chad = "TD"
    Comoros = "KM"
    Egypt = "EG"
    Iraq = "IQ"
    Israel = "IL"
    Jordan = "JO"
    Kuwait = "KW"
    Lebanon = "LB"
    Libya = "LY"
    Mauritania = "MR"
    Morocco = "MA"
    Oman = "OM"
    Palestinian_Authority = "PS"
    Qatar = "QA"
    Saudi_Arabia = "SA"
    Somalia = "SO"
    South_Sudan = "SS"
    Sudan = "SD"
    Syria = "SY"
    Tunisia = "TN"
    UAE = "AE"
    World = "001"
    Yemen = "YE"
    Armenia = "AM"
    India = "IN"
    Spain = "ES"
    Tanzania = "TZ"
    Azerbaijan = "AZ"
    Mali = "ML"
    Bangladesh = "BD"
    Russia = "RU"
    Belarus = "BY"
    Zambia = "ZM"
    Bosnia_and_Herzegovina = "BA"
    Bulgaria = "BG"
    Myanmar = "MM"
    Andorra = "AD"
    Italy = "IT"
    Philippines = "PH"
    Chakma = "Cakm"
    United_States = "US"
    Uganda = "UG"
    People_s_Republic_of_China = "CN"
    Singapore = "SG"
    Hong_Kong_SAR = "HK"
    Taiwan = "TW"
    United_Kingdom = "GB"
    Croatia = "HR"
    Czech_Republic = "CZ"
    Denmark = "DK"
    Greenland = "GL"
    Afghanistan = "AF"
    Maldives = "MV"
    Aruba = "AW"
    Belgium = "BE"
    Bonaire_Sint_Eustatius_and_Saba = "BQ"
    Curaçao = "CW"
    Netherlands = "NL"
    Sint_Maarten = "SX"
    Suriname = "SR"
    Bhutan = "BT"
    Kenya = "KE"
    American_Samoa = "AS"
    Anguilla = "AI"
    Antigua_and_Barbuda = "AG"
    Australia = "AU"
    Austria = "AT"
    Bahamas = "BS"
    Barbados = "BB"
    Belize = "BZ"
    Bermuda = "BM"
    Botswana = "BW"
    British_Indian_Ocean_Territory = "IO"
    British_Virgin_Islands = "VG"
    Burundi = "BI"
    Canada = "CA"
    Caribbean = "029"
    Cayman_Islands = "KY"
    Christmas_Island = "CX"
    Cocos_Keeling_Islands = "CC"
    Cook_Islands = "CK"
    Cyprus = "CY"
    Dominica = "DM"
    Europe = "150"
    Falkland_Islands = "FK"
    Finland = "FI"
    Fiji = "FJ"
    Gambia = "GM"
    Germany = "DE"
    Gibraltar = "GI"
    Grenada = "GD"
    Guam = "GU"
    Guernsey = "GG"
    Guyana = "GY"
    Hong_Kong = "HK"
    Ireland = "IE"
    Isle_of_Man = "IM"
    Jamaica = "JM"
    Jersey = "JE"
    Kiribati = "KI"
    Lesotho = "LS"
    Liberia = "LR"
    Macao_SAR = "MO"
    Madagascar = "MG"
    Malawi = "MW"
    Malaysia = "MY"
    Malta = "MT"
    Marshall_Islands = "MH"
    Mauritius = "MU"
    Micronesia = "FM"
    Montserrat = "MS"
    Nauru = "NR"
    New_Zealand = "NZ"
    Nigeria = "NG"
    Niue = "NU"
    Norfolk_Island = "NF"
    Northern_Mariana_Islands = "MP"
    Pakistan = "PK"
    Palau = "PW"
    Papua_New_Guinea = "PG"
    Pitcairn_Islands = "PN"
    Puerto_Rico = "PR"
    Republic_of_the_Philippines = "PH"
    Rwanda = "RW"
    Saint_Kitts_and_Nevis = "KN"
    Saint_Lucia = "LC"
    Saint_Vincent_and_the_Grenadines = "VC"
    Samoa = "WS"
    Seychelles = "SC"
    Sierra_Leone = "SL"
    Slovenia = "SI"
    Solomon_Islands = "SB"
    St_Helena_Ascension_Tristan_da_Cunha = "SH"
    Swaziland = "SZ"
    Sweden = "SE"
    Tokelau = "TK"
    Tonga = "TO"
    Trinidad_and_Tobago = "TT"
    Turks_and_Caicos_Islands = "TC"
    Tuvalu = "TV"
    United_Arab_Emirates = "AE"
    US_Minor_Outlying_Islands = "UM"
    US_Virgin_Islands = "VI"
    Vanuatu = "VU"
    Zimbabwe = "ZW"
    Estonia = "EE"
    Togo = "TG"
    Faroe_Islands = "FO"
    Benin = "BJ"
    Burkina_Faso = "BF"
    Central_African_Republic = "CF"
    Congo = "CG"
    Congo_DRC = "CD"
    Côte_d_Ivoire = "CI"
    Equatorial_Guinea = "GQ"
    French_Guiana = "GF"
    French_Polynesia = "PF"
    Gabon = "GA"
    Guadeloupe = "GP"
    Guinea = "GN"
    Haiti = "HT"
    Luxembourg = "LU"
    Martinique = "MQ"
    Mayotte = "YT"
    New_Caledonia = "NC"
    Niger = "NE"
    Principality_of_Monaco = "MC"
    Reunion = "RE"
    Saint_Barthélemy = "BL"
    Saint_Martin = "MF"
    Saint_Pierre_and_Miquelon = "PM"
    Senegal = "SN"
    Wallis_and_Futuna = "WF"
    Guinea_Bissau = "GW"
    Georgia = "GE"
    Greece = "GR"
    Paraguay = "PY"
    Hungary = "HU"
    Iceland = "IS"
    Indonesia = "ID"
    San_Marino = "SM"
    Vatican_City = "VA"
    Japan = "JP"
    Latin = "Latn"
    Latin_Indonesia = "ID"
    Cabo_Verde = "CV"
    Brazil = "BR"
    Perso_Arabic = "Arab"
    Kazakhstan = "KZ"
    Cambodia = "KH"
    Guatemala = "GT"
    Korea = "KR"
    North_Korea = "KP"
    Kyrgyzstan = "KG"
    Perso_Arabic_Iran = "IR"
    Lao_PDR = "LA"
    Latvia = "LV"
    Angola = "AO"
    Lithuania = "LT"
    Mozambique = "MZ"
    Brunei_Darussalam = "BN"
    Chile = "CL"
    Iran = "IR"
    Mongolia = "MN"
    Nepal = "NP"
    Colombia = "CO"
    Venezuela = "VE"
    Norway = "NO"
    Svalbard_and_Jan_Mayen = "SJ"
    Cyrillic_Georgia = "GE"
    Cyrillic_Russia = "RU"
    Poland = "PL"
    Portugal = "PT"
    São_Tomé_and_Príncipe = "ST"
    Timor_Leste = "TL"
    Islamic_Republic_of_Pakistan = "PK"
    Bolivia = "BO"
    Ecuador = "EC"
    Peru = "PE"
    Moldova = "MD"
    Romania = "RO"
    Ukraine = "UA"
    Montenegro = "ME"
    Serbia = "RS"
    Serbia_and_Montenegro_Former = "CS"
    Sri_Lanka = "LK"
    Slovakia = "SK"
    Argentina = "AR"
    Bolivarian_Republic_of_Venezuela = "VE"
    Costa_Rica = "CR"
    Cuba = "CU"
    Dominican_Republic = "DO"
    El_Salvador = "SV"
    Honduras = "HN"
    Latin_America = "419"
    Mexico = "MX"
    Nicaragua = "NI"
    Panama = "PA"
    Uruguay = "UY"
    Tifinagh = "Tfng"
    Åland_Islands = "AX"
    Tifinagh_Morocco = "MA"
    Tajikistan = "TJ"
    Thailand = "TH"
    Turkey = "TR"
    Turkmenistan = "TM"
    Perso_Arabic_Afghanistan = "AF"
    Uzbekistan = "UZ"
    Vietnam = "VN"

VALID_LANGUAGE_IDS = {
    'aa', 'aa-DJ', 'aa-ER', 'aa-ET', 'af', 'af-NA', 'af-ZA', 'agq'
    'agq-CM', 'ak', 'ak-GH', 'sq', 'sq-AL', 'sq-MK', 'gsw', 'gsw-FR'
    'gsw-LI', 'gsw-CH', 'am', 'am-ET', 'ar', 'ar-DZ', 'ar-BH', 'ar-TD'
    'ar-KM', 'ar-DJ', 'ar-EG', 'ar-ER', 'ar-IQ', 'ar-IL', 'ar-JO', 'ar-KW'
    'ar-LB', 'ar-LY', 'ar-MR', 'ar-MA', 'ar-OM', 'ar-PS', 'ar-QA', 'ar-SA'
    'ar-SO', 'ar-SS', 'ar-SD', 'ar-SY', 'ar-TN', 'ar-AE', 'ar-001', 'ar-YE'
    'hy', 'hy-AM', 'as', 'as-IN', 'ast', 'ast-ES', 'asa', 'asa-TZ'
    'az-Cyrl', 'az-Cyrl-AZ', 'az', 'az-Latn', 'az-Latn-AZ', 'ksf', 'ksf-CM', 'bm'
    'bm-Latn-ML', 'bn', 'bn-BD', 'bn-IN', 'bas', 'bas-CM', 'ba', 'ba-RU'
    'eu', 'eu-ES', 'be', 'be-BY', 'bem', 'bem-ZM', 'bez', 'bez-TZ'
    'bho', 'bho-Deva', 'bho-Deva-IN', 'byn', 'byn-ER', 'brx', 'brx-IN', 'bs-Cyrl'
    'bs-Cyrl-BA', 'bs-Latn', 'bs', 'bs-Latn-BA', 'br', 'br-FR', 'bg', 'bg-BG'
    'my', 'my-MM', 'ca', 'ca-AD', 'ca-FR', 'ca-IT', 'ca-ES', 'ceb'
    'ceb-Latn', 'ceb-Latn-PH', 'tzm-Arab-MA', 'tzm-Latn-MA', 'ku', 'ku-Arab', 'ku-Arab-IQ', 'ccp'
    'ccp-Cakm', 'ccp-Cakm-BD', 'ccp-Cakm-IN', 'ce-RU', 'chr', 'chr-Cher', 'chr-Cher-US', 'cgg'
    'cgg-UG', 'zh-Hans', 'zh', 'zh-CN', 'zh-SG', 'zh-Hant', 'zh-HK', 'zh-MO'
    'zh-TW', 'cu-RU', 'cv', 'cv-Cyrl', 'cv-Cyrl-RU', 'swc', 'swc-CD', 'kw'
    'kw-GB', 'co', 'co-FR', 'hr', 'hr-HR', 'hr-BA', 'cs', 'cs-CZ'
    'da', 'da-DK', 'da-GL', 'prs', 'prs-AF', 'dv', 'dv-MV', 'dua'
    'dua-CM', 'nl', 'nl-AW', 'nl-BE', 'nl-BQ', 'nl-CW', 'nl-NL', 'nl-SX'
    'nl-SR', 'dz', 'dz-BT', 'ebu', 'ebu-KE', 'en', 'en-AS', 'en-AI'
    'en-AG', 'en-AU', 'en-AT', 'en-BS', 'en-BB', 'en-BE', 'en-BZ', 'en-BM'
    'en-BW', 'en-IO', 'en-VG', 'en-BI', 'en-CM', 'en-CA', 'en-029', 'en-KY'
    'en-CX', 'en-CC', 'en-CK', 'en-CY', 'en-DK', 'en-DM', 'en-ER', 'en-150'
    'en-FK', 'en-FI', 'en-FJ', 'en-GM', 'en-DE', 'en-GH', 'en-GI', 'en-GD'
    'en-GU', 'en-GG', 'en-GY', 'en-HK', 'en-IN', 'en-IE', 'en-IM', 'en-IL'
    'en-JM', 'en-JE', 'en-KE', 'en-KI', 'en-LS', 'en-LR', 'en-MO', 'en-MG'
    'en-MW', 'en-MY', 'en-MV', 'en-MT', 'en-MH', 'en-MU', 'en-FM', 'en-MS'
    'en-NA', 'en-NR', 'en-NL', 'en-NZ', 'en-NG', 'en-NU', 'en-NF', 'en-MP'
    'en-PK', 'en-PW', 'en-PG', 'en-PN', 'en-PR', 'en-PH', 'en-RW', 'en-KN'
    'en-LC', 'en-VC', 'en-WS', 'en-SC', 'en-SL', 'en-SG', 'en-SX', 'en-SI'
    'en-SB', 'en-ZA', 'en-SS', 'en-SH', 'en-SD', 'en-SZ', 'en-SE', 'en-CH'
    'en-TZ', 'en-TK', 'en-TO', 'en-TT', 'en-TC', 'en-TV', 'en-UG', 'en-AE'
    'en-GB', 'en-US', 'en-UM', 'en-VI', 'en-VU', 'en-001', 'en-ZM', 'en-ZW'
    'eo', 'eo-001', 'et', 'et-EE', 'ee', 'ee-GH', 'ee-TG', 'ewo'
    'ewo-CM', 'fo', 'fo-DK', 'fo-FO', 'fil', 'fil-PH', 'fi', 'fi-FI'
    'fr', 'fr-DZ', 'fr-BE', 'fr-BJ', 'fr-BF', 'fr-BI', 'fr-CM', 'fr-CA'
    'fr-029', 'fr-CF', 'fr-TD', 'fr-KM', 'fr-CG', 'fr-CD', 'fr-CI', 'fr-DJ'
    'fr-GQ', 'fr-FR', 'fr-GF', 'fr-PF', 'fr-GA', 'fr-GP', 'fr-GN', 'fr-HT'
    'fr-LU', 'fr-MG', 'fr-ML', 'fr-MQ', 'fr-MR', 'fr-MU', 'fr-YT', 'fr-MA'
    'fr-NC', 'fr-NE', 'fr-MC', 'fr-RE', 'fr-RW', 'fr-BL', 'fr-MF', 'fr-PM'
    'fr-SN', 'fr-SC', 'fr-CH', 'fr-SY', 'fr-TG', 'fr-TN', 'fr-VU', 'fr-WF'
    'fy', 'fy-NL', 'fur', 'fur-IT', 'ff', 'ff-Latn', 'ff-Latn-BF', 'ff-CM'
    'ff-Latn-CM', 'ff-Latn-GM', 'ff-Latn-GH', 'ff-GN', 'ff-Latn-GN', 'ff-Latn-GW', 'ff-Latn-LR', 'ff-MR'
    'ff-Latn-MR', 'ff-Latn-NE', 'ff-NG', 'ff-Latn-NG', 'ff-Latn-SN', 'ff-Latn-SL', 'gl', 'gl-ES'
    'lg', 'lg-UG', 'ka', 'ka-GE', 'de', 'de-AT', 'de-BE', 'de-DE'
    'de-IT', 'de-LI', 'de-LU', 'de-CH', 'el', 'el-CY', 'el-GR', 'kl'
    'kl-GL', 'gn', 'gn-PY', 'gu', 'gu-IN', 'guz', 'guz-KE', 'bgc'
    'bgc-Deva', 'bgc-Deva-IN', 'ha', 'ha-Latn', 'ha-Latn-GH', 'ha-Latn-NE', 'ha-Latn-NG', 'haw'
    'haw-US', 'he', 'he-IL', 'hi', 'hi-IN', 'hi-Latn', 'hi-Latn-IN', 'hu'
    'hu-HU', 'is', 'is-IS', 'ig', 'ig-NG', 'id', 'id-ID', 'ia'
    'ia-FR', 'ia-001', 'iu', 'iu-Latn', 'iu-Latn-CA', 'iu-Cans', 'iu-Cans-CA', 'ga'
    'ga-IE', 'it', 'it-IT', 'it-SM', 'it-CH', 'it-VA', 'ja', 'ja-JP'
    'jv', 'jv-Latn', 'jv-Latn-ID', 'dyo', 'dyo-SN', 'kea', 'kea-CV', 'kab'
    'kab-DZ', 'kgp', 'kgp-Latn', 'kgp-Latn-BR', 'kkj', 'kkj-CM', 'kln', 'kln-KE'
    'kam', 'kam-KE', 'kn', 'kn-IN', 'kr-Latn-NG', 'ks', 'ks-Arab', 'ks-Arab-IN'
    'ks-Deva-IN', 'kk', 'kk-KZ', 'km', 'km-KH', 'quc', 'quc-Latn-GT', 'ki'
    'ki-KE', 'rw', 'rw-RW', 'sw', 'sw-KE', 'sw-TZ', 'sw-UG', 'kok'
    'kok-IN', 'ko', 'ko-KR', 'ko-KP', 'khq', 'khq-ML', 'ses', 'ses-ML'
    'nmg', 'nmg-CM', 'ky', 'ky-KG', 'ku-Arab-IR', 'lkt', 'lkt-US', 'lag'
    'lag-TZ', 'lo', 'lo-LA', 'la-VA', 'lv', 'lv-LV', 'ln', 'ln-AO'
    'ln-CF', 'ln-CG', 'ln-CD', 'lt', 'lt-LT', 'nds', 'nds-DE', 'nds-NL'
    'dsb', 'dsb-DE', 'lu', 'lu-CD', 'luo', 'luo-KE', 'lb', 'lb-LU'
    'luy', 'luy-KE', 'mk', 'mk-MK', 'jmc', 'jmc-TZ', 'mgh', 'mgh-MZ'
    'kde', 'kde-TZ', 'mg', 'mg-MG', 'ms', 'ms-BN', 'ms-MY', 'ml'
    'ml-IN', 'mt', 'mt-MT', 'gv', 'gv-IM', 'mi', 'mi-NZ', 'arn'
    'arn-CL', 'mr', 'mr-IN', 'mas', 'mas-KE', 'mas-TZ', 'mzn-IR', 'mer'
    'mer-KE', 'mgo', 'mgo-CM', 'moh', 'moh-CA', 'mn', 'mn-Cyrl', 'mn-MN'
    'mn-Mong', 'mn-Mong-CN', 'mn-Mong-MN', 'mfe', 'mfe-MU', 'mua', 'mua-CM', 'nqo'
    'nqo-GN', 'naq', 'naq-NA', 'ne', 'ne-IN', 'ne-NP', 'nnh', 'nnh-CM'
    'jgo', 'jgo-CM', 'yrl', 'yrl-Latn', 'yrl-Latn-BR', 'yrl-Latn-CO', 'yrl-Latn-VE', 'lrc-IQ'
    'lrc-IR', 'nd', 'nd-ZW', 'no', 'nb', 'nb-NO', 'nn', 'nn-NO'
    'nb-SJ', 'nus', 'nus-SD', 'nus-SS', 'nyn', 'nyn-UG', 'oc', 'oc-FR'
    'oc-ES', 'or', 'or-IN', 'om', 'om-ET', 'om-KE', 'os', 'os-GE'
    'os-RU', 'ps', 'ps-AF', 'ps-PK', 'fa', 'fa-AF', 'fa-IR', 'pl'
    'pl-PL', 'pt', 'pt-AO', 'pt-BR', 'pt-CV', 'pt-GQ', 'pt-GW', 'pt-LU'
    'pt-MO', 'pt-MZ', 'pt-PT', 'pt-ST', 'pt-CH', 'pt-TL', 'prg-001', 'qps-ploca'
    'qps-ploc', 'qps-plocm', 'pa', 'pa-Arab', 'pa-IN', 'pa-Arab-PK', 'quz', 'quz-BO'
    'quz-EC', 'quz-PE', 'raj', 'raj-Deva', 'raj-Deva-IN', 'ksh', 'ksh-DE', 'ro'
    'ro-MD', 'ro-RO', 'rm', 'rm-CH', 'rof', 'rof-TZ', 'rn', 'rn-BI'
    'ru', 'ru-BY', 'ru-KZ', 'ru-KG', 'ru-MD', 'ru-RU', 'ru-UA', 'rwk'
    'rwk-TZ', 'ssy', 'ssy-ER', 'sah', 'sah-RU', 'saq', 'saq-KE', 'smn'
    'smn-FI', 'smj', 'smj-NO', 'smj-SE', 'se', 'se-FI', 'se-NO', 'se-SE'
    'sms', 'sms-FI', 'sma', 'sma-NO', 'sma-SE', 'sg', 'sg-CF', 'sbp'
    'sbp-TZ', 'sa', 'sa-IN', 'sc', 'sc-Latn', 'sc-Latn-IT', 'gd', 'gd-GB'
    'seh', 'seh-MZ', 'sr-Cyrl', 'sr-Cyrl-BA', 'sr-Cyrl-ME', 'sr-Cyrl-RS', 'sr-Cyrl-CS', 'sr-Latn'
    'sr', 'sr-Latn-BA', 'sr-Latn-ME', 'sr-Latn-RS', 'sr-Latn-CS', 'nso', 'nso-ZA', 'tn'
    'tn-BW', 'tn-ZA', 'ksb', 'ksb-TZ', 'sn', 'sn-Latn', 'sn-Latn-ZW', 'sd'
    'sd-Arab', 'sd-Arab-PK', 'si', 'si-LK', 'sk', 'sk-SK', 'sl', 'sl-SI'
    'xog', 'xog-UG', 'so', 'so-DJ', 'so-ET', 'so-KE', 'so-SO', 'st'
    'st-ZA', 'nr', 'nr-ZA', 'st-LS', 'es', 'es-AR', 'es-BZ', 'es-VE'
    'es-BO', 'es-BR', 'es-CL', 'es-CO', 'es-CR', 'es-CU', 'es-DO', 'es-EC'
    'es-SV', 'es-GQ', 'es-GT', 'es-HN', 'es-419', 'es-MX', 'es-NI', 'es-PA'
    'es-PY', 'es-PE', 'es-PH', 'es-PR', 'es-ES_tradnl', 'es-ES', 'es-US', 'es-UY'
    'zgh', 'zgh-Tfng-MA', 'zgh-Tfng', 'ss', 'ss-ZA', 'ss-SZ', 'sv', 'sv-AX'
    'sv-FI', 'sv-SE', 'syr', 'syr-SY', 'shi', 'shi-Tfng', 'shi-Tfng-MA', 'shi-Latn'
    'shi-Latn-MA', 'dav', 'dav-KE', 'tg', 'tg-Cyrl', 'tg-Cyrl-TJ', 'tzm', 'tzm-Latn'
    'tzm-Latn-DZ', 'ta', 'ta-IN', 'ta-MY', 'ta-SG', 'ta-LK', 'twq', 'twq-NE'
    'tt', 'tt-RU', 'te', 'te-IN', 'teo', 'teo-KE', 'teo-UG', 'th'
    'th-TH', 'bo', 'bo-IN', 'bo-CN', 'tig', 'tig-ER', 'ti', 'ti-ER'
    'ti-ET', 'to', 'to-TO', 'ts', 'ts-ZA', 'tr', 'tr-CY', 'tr-TR'
    'tk', 'tk-TM', 'uk', 'uk-UA', 'hsb', 'hsb-DE', 'ur', 'ur-IN'
    'ur-PK', 'ug', 'ug-CN', 'uz-Arab', 'uz-Arab-AF', 'uz-Cyrl', 'uz-Cyrl-UZ', 'uz'
    'uz-Latn', 'uz-Latn-UZ', 'vai', 'vai-Vaii', 'vai-Vaii-LR', 'vai-Latn-LR', 'vai-Latn', 'ca-ES-valencia'
    've', 've-ZA', 'vi', 'vi-VN', 'vo', 'vo-001', 'vun', 'vun-TZ'
    'wae', 'wae-CH', 'cy', 'cy-GB', 'wal', 'wal-ET', 'wo', 'wo-SN'
    'xh', 'xh-ZA', 'yav', 'yav-CM', 'ii', 'ii-CN', 'yi-001', 'yo'
    'yo-BJ', 'yo-NG', 'dje', 'dje-NE', 'zu', 'zu-ZA'
}
